#pragma once
#include <windows.h>
#include <chrono>
#include <iostream>
#include <thread>
#include <conio.h>


// Color 參考
//https://blog.wildsky.cc/posts/c-code-note/ 

enum Color {  // Col_字體顏色_背景顏色 //沒有背景顏色則為黑色
    Col_darkblue      = 1,
    Col_darkgreen     = 2,
    Col_darkBlueGreen = 3,
    Col_darkred       = 4,
    Col_purple        = 5,
    Col_shit          = 6,
    Col_RESET         = 7,
    Col_gray          = 8,
    Col_blue          = 9,
    Col_lightgreen    = 10,
    Col_lightblue     = 11,
    Col_red           = 12,
    Col_pink          = 13,
    Col_yellow        = 14,
    Col_white         = 15,
    Col_darkblue_black         = 16,
    Col_darkblue_darkblue      = 17,
    Col_darkblue_darkgreen     = 18,
    Col_darkblue_darkBlueGreen = 19,
    Col_darkblue_darkred       = 20,
    Col_darkblue_purple        = 21,
    Col_darkblue_shit          = 22,
    Col_darkblue_RESET         = 23,
    Col_darkblue_gray          = 24,
    Col_darkblue_blue          = 25,
    Col_darkblue_lightgreen    = 26,
    Col_darkblue_lightblue     = 27,
    Col_darkblue_red           = 28,
    Col_darkblue_pink          = 29,
    Col_darkblue_yellow        = 30,
    Col_darkblue_white         = 31,
    Col_darkgreen_black         = 32,
    Col_darkgreen_darkblue      = 33,
    Col_darkgreen_darkgreen     = 34,
    Col_darkgreen_darkBlueGreen = 35,
    Col_darkgreen_darkred       = 36,
    Col_darkgreen_purple        = 37,
    Col_darkgreen_shit          = 38,
    Col_darkgreen_RESET         = 39,
    Col_darkgreen_gray          = 40,
    Col_darkgreen_blue          = 41,
    Col_darkgreen_lightgreen    = 42,
    Col_darkgreen_lightblue     = 43,
    Col_darkgreen_red           = 44,
    Col_darkgreen_pink          = 45,
    Col_darkgreen_yellow        = 46,
    Col_darkgreen_white         = 47,
    Col_darkBlueGreen_black         = 48,
    Col_darkBlueGreen_darkblue      = 49,
    Col_darkBlueGreen_darkgreen     = 50,
    Col_darkBlueGreen_darkBlueGreen = 51,
    Col_darkBlueGreen_darkred       = 52,
    Col_darkBlueGreen_purple        = 53,
    Col_darkBlueGreen_shit          = 54,
    Col_darkBlueGreen_RESET         = 55,
    Col_darkBlueGreen_gray          = 56,
    Col_darkBlueGreen_blue          = 57,
    Col_darkBlueGreen_lightgreen    = 58,
    Col_darkBlueGreen_lightblue     = 59,
    Col_darkBlueGreen_red           = 60,
    Col_darkBlueGreen_pink          = 61,
    Col_darkBlueGreen_yellow        = 62,
    Col_darkBlueGreen_white         = 63,
    Col_darkred_black         = 64,
    Col_darkred_darkblue      = 65,
    Col_darkred_darkgreen     = 66,
    Col_darkred_darkBlueGreen = 67,
    Col_darkred_darkred       = 68,
    Col_darkred_purple        = 69,
    Col_darkred_shit          = 70,
    Col_darkred_RESET         = 71,
    Col_darkred_gray          = 72,
    Col_darkred_blue          = 73,
    Col_darkred_lightgreen    = 74,
    Col_darkred_lightblue     = 75,
    Col_darkred_red           = 76,
    Col_darkred_pink          = 77,
    Col_darkred_yellow        = 78,
    Col_darkred_white         = 79,
    Col_purple_black         = 80,
    Col_purple_darkblue      = 81,
    Col_purple_darkgreen     = 82,
    Col_purple_darkBlueGreen = 83,
    Col_purple_darkred       = 84,
    Col_purple_purple        = 85,
    Col_purple_shit          = 86,
    Col_purple_RESET         = 87,
    Col_purple_gray          = 88,
    Col_purple_blue          = 89,
    Col_purple_lightgreen    = 90,
    Col_purple_lightblue     = 91,
    Col_purple_red           = 92,
    Col_purple_pink          = 93,
    Col_purple_yellow        = 94,
    Col_purple_white         = 95,
    Col_shit_black         = 96,
    Col_shit_darkblue      = 97,
    Col_shit_darkgreen     = 98,
    Col_shit_darkBlueGreen = 99,
    Col_shit_darkred        = 100,
    Col_shit_purple         = 101,
    Col_shit_shit           = 102,
    Col_shit_RESET          = 103,
    Col_shit_gray           = 104,
    Col_shit_blue           = 105,
    Col_shit_lightgreen     = 106,
    Col_shit_lightblue      = 107,
    Col_shit_red            = 108,
    Col_shit_pink           = 109,
    Col_shit_yellow         = 110,
    Col_shit_white          = 111,
    Col_RESET_black         = 112,
    Col_RESET_darkblue      = 113,
    Col_RESET_darkgreen     = 114,
    Col_RESET_darkBlueGreen = 115,
    Col_RESET_darkred       = 116,
    Col_RESET_purple        = 117,
    Col_RESET_shit          = 118,
    Col_RESET_RESET         = 119,
    Col_RESET_gray          = 120,
    Col_RESET_blue          = 121,
    Col_RESET_lightgreen    = 122,
    Col_RESET_lightblue     = 123,
    Col_RESET_red           = 124,
    Col_RESET_pink          = 125,
    Col_RESET_yellow        = 126,
    Col_RESET_white         = 127,
    Col_gray_black         = 128,
    Col_gray_darkblue      = 129,
    Col_gray_darkgreen     = 130,
    Col_gray_darkBlueGreen = 131,
    Col_gray_darkred       = 132,
    Col_gray_purple        = 133,
    Col_gray_shit          = 134,
    Col_gray_RESET         = 135,
    Col_gray_gray          = 136,
    Col_gray_blue          = 137,
    Col_gray_lightgreen    = 138,
    Col_gray_lightblue     = 139,
    Col_gray_red           = 140,
    Col_gray_pink          = 141,
    Col_gray_yellow        = 142,
    Col_gray_white         = 143,
    Col_blue_black         = 144,
    Col_blue_darkblue      = 145,
    Col_blue_darkgreen     = 146,
    Col_blue_darkBlueGreen = 147,
    Col_blue_darkred       = 148,
    Col_blue_purple        = 149,
    Col_blue_shit          = 150,
    Col_blue_RESET         = 151,
    Col_blue_gray          = 152,
    Col_blue_blue          = 153,
    Col_blue_lightgreen    = 154,
    Col_blue_lightblue     = 155,
    Col_blue_red           = 156,
    Col_blue_pink          = 157,
    Col_blue_yellow        = 158,
    Col_blue_white         = 159,
    Col_lightgreen_black         = 160,
    Col_lightgreen_darkblue      = 161,
    Col_lightgreen_darkgreen     = 162,
    Col_lightgreen_darkBlueGreen = 163,
    Col_lightgreen_darkred       = 164,
    Col_lightgreen_purple        = 165,
    Col_lightgreen_shit          = 166,
    Col_lightgreen_RESET         = 167,
    Col_lightgreen_gray          = 168,
    Col_lightgreen_blue          = 169,
    Col_lightgreen_lightgreen    = 170,
    Col_lightgreen_lightblue     = 171,
    Col_lightgreen_red           = 172,
    Col_lightgreen_pink          = 173,
    Col_lightgreen_yellow        = 174,
    Col_lightgreen_white         = 175,
    Col_lightblue_black         = 176,
    Col_lightblue_darkblue      = 177,
    Col_lightblue_darkgreen     = 178,
    Col_lightblue_darkBlueGreen = 179,
    Col_lightblue_darkred       = 180,
    Col_lightblue_purple        = 181,
    Col_lightblue_shit          = 182,
    Col_lightblue_RESET         = 183,
    Col_lightblue_gray          = 184,
    Col_lightblue_blue          = 185,
    Col_lightblue_lightgreen    = 186,
    Col_lightblue_lightblue     = 187,
    Col_lightblue_red           = 188,
    Col_lightblue_pink          = 189,
    Col_lightblue_yellow        = 190,
    Col_lightblue_white         = 191,
    Col_red_black         = 192,
    Col_red_darkblue      = 193,
    Col_red_darkgreen     = 194,
    Col_red_darkBlueGreen = 195,
    Col_red_darkred       = 196,
    Col_red_purple        = 197,
    Col_red_shit          = 198,
    Col_red_RESET         = 199,
    Col_red_gray          = 200,
    Col_red_blue          = 201,
    Col_red_lightgreen    = 202,
    Col_red_lightblue     = 203,
    Col_red_red           = 204,
    Col_red_pink          = 205,
    Col_red_yellow        = 206,
    Col_red_white         = 207,
    Col_pink_black         = 208,
    Col_pink_darkblue      = 209,
    Col_pink_darkgreen     = 210,
    Col_pink_darkBlueGreen = 211,
    Col_pink_darkred       = 212,
    Col_pink_purple        = 213,
    Col_pink_shit          = 214,
    Col_pink_RESET         = 215,
    Col_pink_gray          = 216,
    Col_pink_blue          = 217,
    Col_pink_lightgreen    = 218,
    Col_pink_lightblue     = 219,
    Col_pink_red           = 220,
    Col_pink_pink          = 221,
    Col_pink_yellow        = 222,
    Col_pink_white         = 223,
    Col_yellow_black         = 224,
    Col_yellow_darkblue      = 225,
    Col_yellow_darkgreen     = 226,
    Col_yellow_darkBlueGreen = 227,
    Col_yellow_darkred       = 228,
    Col_yellow_purple        = 229,
    Col_yellow_shit          = 230,
    Col_yellow_RESET         = 231,
    Col_yellow_gray          = 232,
    Col_yellow_blue          = 233,
    Col_yellow_lightgreen    = 234,
    Col_yellow_lightblue     = 235,
    Col_yellow_red           = 236,
    Col_yellow_pink          = 237,
    Col_yellow_yellow        = 238,
    Col_yellow_white         = 239,
    Col_white_black         = 240,
    Col_white_darkblue      = 241,
    Col_white_darkgreen     = 242,
    Col_white_darkBlueGreen = 243,
    Col_white_darkred       = 244,
    Col_white_purple        = 245,
    Col_white_shit          = 246,
    Col_white_RESET         = 247,
    Col_white_gray          = 248,
    Col_white_blue          = 249,
    Col_white_lightgreen    = 250,
    Col_white_lightblue     = 251,
    Col_white_red           = 252,
    Col_white_pink          = 253,
    Col_white_yellow        = 254,
    Col_ALLWH_white         = 255
};


class Tools
{
public:
	// 位置設定
	static COORD getCursorPosition(HANDLE hConsoleOutput);
    static void  gotoXY(int xpos, int ypos);
    static void  gotoX(int xpos);
    static void  gotoY(int ypos);

    static void  clearX(int xpos);

	static COORD getpos();

	// 顏色
	static void SetColor(int color = 7);

	//延遲
	static void sleepMilsec(int milsec);

    //光標
    static void hideCursor();
    static void showCursor();
    

};

